language: ruby
script:
  - 'bundle exec rake validate'
  - 'bundle exec rake spec'
  - 'bundle exec rake lint'
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
  - 2.1
  - 2.2
env:
  - PUPPET_VERSION=2.7.26
  - PUPPET_VERSION=3.8.7
  - PUPPET_VERSION=4.4.2
gemfile: .travis/Gemfile
matrix:
  exclude:
    - rvm: 1.8.7
      env: PUPPET_VERSION=4.4.2
    - rvm: 2.0.0
      env: PUPPET_VERSION=2.7.26
    - rvm: 2.1
      env: PUPPET_VERSION=2.7.26
    - rvm: 2.2
      env: PUPPET_VERSION=2.7.26
    - rvm: 2.2
      env: PUPPET_VERSION=3.8.7
