language: ruby
script:   "rake spec"
rvm:
  - 1.8.7
  - 1.9.3
  - 2.0.0
env:
  - PUPPET_VERSION=2.7.22
  - PUPPET_VERSION=3.2.2
matrix:
  allow_failures:
    - rvm: 2.0.0
      env: PUPPET_VERSION=2.7.22
gemfile: .travis/Gemfile

